--INSERT INTO [dbo].[TB_CLIENTE]  ([NOME] ,[RG] ,[CPF]  ,[DATA_NASCIMENTO]  ,[TELEFONE] ,[EMAIL],[COD_EMPRESA])
--VALUES
--()


--INSERT INTO [dbo].[TB_ENDERECO] ([RUA]  ,[BAIRRO] ,[NUMERO] ,[COMPLEMENTO]  ,[CEP] ,[TIPO_ENDERECO] ,[cidade_Id])
--     VALUES
--           ()



--INSERT INTO [dbo].[CLIENTE_EMPRESA]   ([TB_CLIENTE_ID]  ,[TB_ENDERECO_ID])
--     VALUES
--           ()